"""Generate the dependency-free symbol module consumed by GDB."""

from __future__ import annotations

import pprint
from pathlib import Path
from typing import Any

from .common import ROOT, load_yaml, resolve

_SYMBOL_FILES = {
    "functions": "re/symbols/functions.yml",
    "globals": "re/symbols/globals.yml",
    "data": "re/symbols/data.yml",
    "strings": "re/symbols/strings.yml",
}


def _address(value: Any, *, source: str, name: str) -> int:
    try:
        return int(value, 0) if isinstance(value, str) else int(value)
    except (TypeError, ValueError) as exc:
        raise ValueError(f"{source}: {name} has invalid address {value!r}") from exc


def _aliases(item: dict[str, Any], *, source: str, name: str) -> list[str]:
    aliases = item.get("gdb_aliases", [])
    if isinstance(aliases, str):
        aliases = [aliases]
    if not isinstance(aliases, list) or any(not isinstance(alias, str) or not alias for alias in aliases):
        raise ValueError(f"{source}: {name} gdb_aliases must be a list of non-empty strings")
    return aliases


def _category(root: Path, key: str) -> tuple[dict[str, int], dict[str, dict[str, Any]], dict[str, str]]:
    source_path = root / _SYMBOL_FILES[key]
    document = load_yaml(source_path)
    values: dict[str, int] = {}
    metadata: dict[str, dict[str, Any]] = {}
    aliases: dict[str, str] = {}
    addresses: dict[int, str] = {}
    for item in document.get(key, []):
        if not isinstance(item, dict):
            raise TypeError(f"{source_path}: each {key} entry must be a mapping")
        try:
            name = str(item["name"])
        except KeyError as exc:
            raise ValueError(f"{source_path}: {key} entry is missing name") from exc
        if name in values:
            raise ValueError(f"{source_path}: duplicate {key} name {name!r}")
        address = _address(item.get("address"), source=str(source_path), name=name)
        previous = addresses.get(address)
        if previous is not None:
            raise ValueError(f"{source_path}: {key} entries {previous!r} and {name!r} share address 0x{address:08x}")
        addresses[address] = name
        values[name] = address
        metadata[name] = {
            field: value for field, value in item.items() if field not in {"address", "name", "gdb_aliases"}
        }
        for alias in _aliases(item, source=str(source_path), name=name):
            previous = aliases.get(alias)
            if previous is not None and previous != name:
                raise ValueError(f"{source_path}: alias {alias!r} names both {previous!r} and {name!r}")
            aliases[alias] = name
    return values, metadata, aliases


def _build_sha256(root: Path) -> str:
    config = load_yaml(root / "re/config/binaries.yml")
    return str(config.get("executables", {}).get("thps2_pc", {}).get("sha256", "unknown"))


def load_symbol_database(root: Path = ROOT) -> dict[str, Any]:
    """Load and validate all tracked symbol categories."""

    root = Path(root).resolve()
    database: dict[str, Any] = {"BUILD_SHA256": _build_sha256(root)}
    for key in _SYMBOL_FILES:
        values, metadata, aliases = _category(root, key)
        database[key.upper()] = values
        database[f"{key.upper()}_METADATA"] = metadata
        database[f"{key.upper()}_ALIASES"] = aliases
    return database


def _render_mapping(name: str, values: dict[str, int]) -> list[str]:
    lines = [f"{name} = {{"]
    for key, value in values.items():
        lines.append(f"    {key!r}: 0x{value:08x},")
    lines.append("}")
    return lines


def _render_object(name: str, value: Any) -> list[str]:
    rendered = pprint.pformat(value, sort_dicts=False, width=120)
    return [f"{name} = {rendered}"]


def render_knowledge(database: dict[str, Any]) -> str:
    """Render a Python module using only literals and stdlib-compatible syntax."""

    lines = [
        '"""Generated by ``tony gdb generate``; do not edit by hand."""',
        "",
        f"BUILD_SHA256 = {database['BUILD_SHA256']!r}",
        "",
    ]
    for category in ("FUNCTIONS", "GLOBALS", "DATA", "STRINGS"):
        lines.extend(_render_mapping(category, database[category]))
        lines.append("")
    for category in ("FUNCTIONS", "GLOBALS", "DATA", "STRINGS"):
        lines.extend(_render_object(f"{category}_METADATA", database[f"{category}_METADATA"]))
        lines.append("")
        lines.extend(_render_object(f"{category}_ALIASES", database[f"{category}_ALIASES"]))
        lines.append("")
    return "\n".join(lines)


def generate(output: str | Path | None = None) -> Path:
    """Generate ``build/gdb/knowledge.py`` and return its path."""

    target = resolve(output or "build/gdb/knowledge.py")
    database = load_symbol_database(ROOT)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(render_knowledge(database), encoding="utf-8")
    print(f"Generated GDB knowledge: {target}")
    return target
