#!/usr/bin/env python3
"""Generate the VC6-friendly capture hook table from the YAML manifest."""

from __future__ import annotations

import sys
from pathlib import Path

import yaml


def _u32(value: int | str) -> int:
    return int(value, 0) if isinstance(value, str) else int(value)


def _bytes(text: str) -> list[int]:
    return [int(part, 16) for part in text.split()]


def generate(source: Path) -> str:
    manifest = yaml.safe_load(source.read_text())
    hooks = manifest["hooks"]
    lines = [
        "/* Generated by scripts/generate_capture_hooks.py; do not edit. */",
        "#ifndef OPENTONY_CAPTURE_HOOKS_GENERATED_H",
        "#define OPENTONY_CAPTURE_HOOKS_GENERATED_H",
        '#include "hooks.h"',
        "",
        "static const CaptureHookSpec k_hooks[] = {",
    ]
    for name, hook in hooks.items():
        expected = _bytes(hook["expected"])
        if len(expected) > 16:
            raise ValueError(f"{name}: expected bytes exceed CaptureHookSpec capacity")
        expected_padded = expected + [0] * (16 - len(expected))
        relocations = [_u32(offset) for offset in hook.get("relocate_rel32", [])]
        if len(relocations) > 4:
            raise ValueError(f"{name}: too many rel32 relocation offsets")
        overwrite = _u32(hook["overwrite"])
        for offset in relocations:
            if offset + 5 > overwrite or offset + 5 > len(expected):
                raise ValueError(f"{name}: rel32 relocation is outside expected bytes")
            if expected[offset] not in (0xE8, 0xE9):
                raise ValueError(f"{name}: relocation does not point at E8/E9")
        relocations += [0] * (4 - len(relocations))
        lines.extend(
            [
                "    {",
                f'        "{name}",',
                f"        0x{_u32(hook['rva']):08x}u,",
                "        {" + ", ".join(f"0x{byte:02x}" for byte in expected_padded) + "},",
                f"        {len(expected)}u,",
                f"        {overwrite}u,",
                "        {" + ", ".join(str(offset) for offset in relocations) + "},",
                f"        {len(hook.get('relocate_rel32', []))}u,",
                "    },",
            ]
        )
    lines.extend(["};", "", "#endif /* OPENTONY_CAPTURE_HOOKS_GENERATED_H */", ""])
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    if len(argv) not in (2, 3):
        print(f"usage: {argv[0]} MANIFEST [OUTPUT]", file=sys.stderr)
        return 2
    output = Path(argv[2]) if len(argv) == 3 else None
    rendered = generate(Path(argv[1]))
    if output is None:
        sys.stdout.write(rendered)
    else:
        output.write_text(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
