#pragma once

#include <array>
#include <cstddef>
#include <cstdint>
#include <optional>
#include <stdexcept>
#include <span>
#include <string>
#include <vector>

namespace opentony::assets {

class TricksBinFormatError final : public std::runtime_error {
public:
    explicit TricksBinFormatError(const std::string& message)
        : std::runtime_error(message) {}
};

// The retail tricks.bin loader at FUN_00492a90 treats the first eight
// signed-16-bit words as byte offsets into the loaded image. Section 0 starts
// with the signed table used by FUN_004bcf00 to select a player-input
// sequence table; the records in those tables carry direct image-relative
// action-stream offsets. Later sections contain metadata, generated-table
// destinations, and the heap-object source database.
struct TricksBinHeader final {
    std::array<std::int16_t, 8> section_offsets{};

    [[nodiscard]] std::int16_t action_offset_table_offset() const noexcept {
        return section_offsets[0];
    }
    [[nodiscard]] std::int16_t action_metadata_offset() const noexcept {
        return section_offsets[1];
    }
};

struct TricksBinView final {
    std::span<const std::uint8_t> bytes{};
    TricksBinHeader header{};
    bool valid{};

    // DAT_00568868 is a signed-16-bit stream-offset table. The selected value
    // is added directly to DAT_0056a894, the loaded image address.
    [[nodiscard]] std::optional<std::int16_t> action_lookup(
        std::size_t index) const noexcept;

    // FUN_004bcf00 resolves the selected player/resource index through the
    // section-0 table and passes the resulting short-record table to
    // FUN_004bc3a0. This is the actual input to the generated per-player
    // table builder, not an action command stream.
    [[nodiscard]] std::optional<std::span<const std::uint8_t>>
    player_input_sequence_table(std::size_t index) const noexcept;

    // Returns the remaining image from a lookup-resolved stream start. The
    // stream's 0x07 terminator, not a fabricated length, bounds execution.
    [[nodiscard]] std::optional<std::span<const std::uint8_t>> action_stream(
        std::int16_t relative_offset) const noexcept;

    [[nodiscard]] std::optional<std::span<const std::uint8_t>> action_stream_for_lookup(
        std::size_t index) const noexcept;

    // Header sections 6 and 5 are shipped source sequence tables. They use
    // the same [length][action IDs...][stream-relative][flags] records as the
    // generated player table, but are not the per-player destinations at
    // header sections 3 and 4. Section 5 is the heap-object source database;
    // section 6 is the alternate source table used by the other player path.
    [[nodiscard]] std::optional<std::span<const std::uint8_t>> source_sequence_table()
        const noexcept;
    [[nodiscard]] std::optional<std::span<const std::uint8_t>> alternate_sequence_table()
        const noexcept;

    // Header word 7 points at the special alternate-resource table used by
    // FUN_004bbf00 when its mode argument is nonzero. Its leading word is
    // not the ordinary action-table record length (the shipped image starts
    // with 0x0100), so expose the bounded raw section until that format is
    // recovered instead of passing it through bounded_sequence_table().
    [[nodiscard]] std::optional<std::span<const std::uint8_t>>
    special_other_resource_table() const noexcept;

    // The loader stores the generated per-player/other-player table
    // destinations from header words 3 and 4. In the shipped file these
    // sections are zero-filled placeholders; FUN_004bd1e0 replaces them in
    // heap memory before FUN_004925e0 consumes them. These views are useful
    // for fixtures and for callers that provide captured/generated bytes.
    [[nodiscard]] std::optional<std::span<const std::uint8_t>> player_sequence_table()
        const noexcept;
    [[nodiscard]] std::optional<std::span<const std::uint8_t>> other_player_sequence_table()
        const noexcept;
};

[[nodiscard]] TricksBinView parse_tricks_bin(
    std::span<const std::uint8_t> bytes) noexcept;

// Owns a loaded PC tricks.bin image. The view is reconstructed on demand so
// it never retains a pointer across a vector move.
class TricksBinArchive final {
public:
    static TricksBinArchive load(const std::string& path);
    static TricksBinArchive parse(
        std::vector<std::uint8_t> bytes,
        std::string source = {});

    [[nodiscard]] TricksBinView view() const noexcept {
        return parse_tricks_bin(bytes_);
    }
    [[nodiscard]] const std::vector<std::uint8_t>& bytes() const noexcept {
        return bytes_;
    }

private:
    std::vector<std::uint8_t> bytes_;
    std::string source_;
};

} // namespace opentony::assets
